name: Build, and Run

on:
  push:
  pull_request:

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build project
      run: |
        pip install build
        python -m build

    - name: Install built package
      run: |
        pip install dist/*.whl

    - name: Run to check it at least starts
      run: |
        refrapt --version
